//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_2022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalculatingEntities : DbContext
    {
        private static CalculatingEntities _context;

        public CalculatingEntities()
            : base("name=CalculatingEntities")
        {
        }

        public static CalculatingEntities GetContext()
        {
            if (_context == null)
                _context = new CalculatingEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Control_Employes> Control_Employes { get; set; }
        public virtual DbSet<Control_Tasks> Control_Tasks { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
